---
 
- hosts: web
  vars: 
    package_name:
      - apache2
      - mysql-server
  tasks:
  - name: install packages
    tags: packages
    ansible.builtin.apt:
      pkg:
       - apache2
       - mysql-server
       - php
       - wget
       - unzip
       
  - name: install reqired packages for pip
    tags: pip,database
    ansible.builtin.apt:
      pkg:
       - pkg-config
       - libmysqlclient-dev
       
                 
      state: present
  - name: start packages service
    tags: start 
    ansible.builtin.service:
      name: "{{item}}"
      state: started
      enabled: yes
    loop: "{{package_name}}"
  
  - name: delete files of html
    tags: wordpress,delete
    ansible.builtin.file:
      path: /var/www/html
      state: absent
  - name: create new html directory
    tags: wordpress,create
    ansible.builtin.file:
      path: /var/www/html
      state: directory
      owner: www-data
      group: www-data

  - name: insert files of wordpress
    tags: wordpress,get
    ansible.builtin.unarchive:
      src: https://wordpress.org/latest.zip
      dest: /var/www/html
      owner: www-data
      group: www-data
      remote_src: true
  - name: change file location
    tags: wordpress,get
    ansible.builtin.copy:
      src: /var/www/html/wordpress/
      dest: /var/www/html
      owner: www-data
      group: www-data
      remote_src: true
 
  - name: change permissions
    tags: wordpress,perm
    ansible.builtin.file:
      path: /var/www
      owner:  www-data
      group:  www-data
  - name: create wp-config.php file
    tags: wordpress,rename 
    ansible.builtin.copy:
      src: /var/www/html/wp-config-sample.php
      dest: /var/www/html/wp-config.php
      remote_src: true 

      


  - name: Update DB_name in wp-config.php
    tags: wordpress,cred
    ansible.builtin.lineinfile:
        path: /var/www/html/wp-config.php
        search_string: 'database_name_here'
        line: "define( 'DB_NAME', 'wordpress' );"
        state: present

  - name: Update DB_user in wp-config.php
    tags: wordpress,cred
    ansible.builtin.lineinfile:
        path: /var/www/html/wp-config.php
        search_string: 'username_here'
        line: "define( 'DB_USER', 'wordpress' );"
        state: present
         
  - name : Update DB_PASSWORD in wp-config.php
    tags: wordpress,cred
    ansible.builtin.lineinfile:
        path: /var/www/html/wp-config.php
        search_string: 'password_here'
        line: "define( 'DB_PASSWORD', 'password' );"
        state: present
  - name: install required package to connect to mysql database
    tags: database,pip
    ansible.builtin.pip:
        name: mysqlclient
  - name: create database
    tags: database
    community.mysql.mysql_db:
       name: wordpress
       state: present
  - name: add user and give it all privilages
    tags: database
    community.mysql.mysql_user:
       name: wordpress
       password: password
       host: localhost
       priv: "wordpress.*:ALL"
       state: present

  - name: restart apache2
    tags: wordpress, restart
    ansible.builtin.service:
      name: apache2
      state: restarted 
      
