apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: vhmds/front-end
        securityContext:
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: my-app
spec:
  selector:
    app: front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
