apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6.8
        securityContext:
          capabilities:
            drop: ["ALL"]
            add: ["CHOWN", "SETGID", "SETUID", "DAC_OVERRIDE"]
          readOnlyRootFilesystem: true
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: my-app
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
    - protocol: TCP
      port: 15672
      targetPort: 15672
